### ISSUE TITLE
no visible thumbnail after encoding

### ISSUE THREAD

**Issue by littlefico** [L0Lock/FFmpeg-bat-collection#1]
i tested your dragndrop to android and was fascinated how it compresses my video from 10mb to 1,x mb. amazing!!!

i noticed the preview thumbnail was missing. while no error i am curious how it would look like with enabled preview thumbnail in windows.
thx

**Comment by L0Lock** [comment]
I'm glad you enjoy my scipt!  
Concerning the thumbnails, unfortunately there isn't much I can do. I try to use the best compromise between audio&video quality, file size and compatibility on as much android devices as possible.

The best I can do is to ask you which device you're using and if the problem persists using different applications or with different videos made with the script. And see what we can do after that.

Eventually, I could make a seperate script that would force create a thumbnail and write it inside the video file. It would be a dirty way, and depending the device and the app used it might still not be enough, but it's a way.

**Comment by littlefico** [comment]
it´s really no deal. i was just curious because i didnt see the preview in windows 10 (newest build) while the orig file was next to the file with a visible thumbnail.
so it´s really no deal. (standard application is VLC)

**Comment by L0Lock** [comment]
Ok then ^^
I shall close this ticket then. Fell free to report any other issue.
